export const data = [
    {
        id:1,
        name:"Banane",
        categorie:"Fruit",
        amount:50,
        description:"C'est le fruit idéal pour le sport du fait de son excellent apport en glucides accompagné d'une bonne concentration minérale (potassium, magnésium). Sa valeur énergétique atteint les 90 kilocalories pour 100 grammes.",
        imageSource:require("./Images/Fruits/banane.png"),
        price:1000,
        count:0,
    },
    {
        id:2,
        name:"Poivre",
        categorie:'Epices',
        amount:50,
        description:"Stimulant : le poivre aide à la digestion en favorisant la sécrétion de sucs gastriques. Son utilisation est indiquée en cas de nausées, ballonnements, flatulences, constipation et manque d'appétit.",
        imageSource:require("./Images/Épices/poivre.png"),
        price:1000,
        count:0,
    },
    {
        id:3,
        name:"Carotte",
        categorie:'Legumes',
        amount:50,
        description:"est un légume peu énergétique (33 kilocalories pour 100 grammes) et présente de nombreuses vitamines dont une grande richesse en provitamine A, en minéraux (potassium) et en fibres. Ses taux en vitamines et en antioxydants auraient un rôle dans la prévention des maladies cardiovasculaires et de cancers.",
        imageSource:require("./Images/Legumes/carottes.png"),
        price:1000,
        count:0,
    },
    {
        id:4,
        name:"Manioc",
        categorie:"Plantes",
        amount:50,
        description:"La teneur en amidon importante du manioc le rend facilement digestible, il va aussi aider à réguler les problèmes de diarrhées ou d'irritation du côlon.",
        imageSource:require("./Images/Plantes/feuilleManioc.png"),
        price:1000,
        count:0,
    }
]
